\set ON_ERROR_STOP on
GRANT USAGE ON SCHEMA public TO brandflow_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO brandflow_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO brandflow_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO brandflow_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO brandflow_app;
